pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    // Use the absolute path to Maven
                    sh '/path/to/maven/bin/mvn clean validate compile install test package'
                }
            }
        }
    }
}