pipeline {
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('Sonar-scan'){
            steps {
                 withSonarQubeEnv('sonarQube') { // Ensure this matches the SonarQube configuration name
                    sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                    -Dsonar.projectKey=Guilene2022_geo-app'
                 }

            }

        }
        stage('maven'){
            steps{
                sh 'mvn clean validate compile install test package'
                }
            
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP8jo9ZFcrg81cCsXRTSHJL87ta -T \
                 target/bio*.jar \
                 "http://54.237.207.209:8081/artifactory/geo-app/bio_${BUILD_ID}.jar"'

            }
        }
        

    }

}
   